version: 2.1
jobs:
  rubocop2:
    steps:
      - checkout
      - rubocop/lint

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

# orbs:jobsのパッケージ
orbs:
  heroku: circleci/heroku@1.2.4
  rubocop: boxt/rubocop@0.3.0

# workflows:jobsの実行順番
workflows:
  version: 2.1
  build:
    jobs:
      - rubocop2
      - heroku_deploy:
          requires:
            - rubocop2
