version: 2.1
jobs:
  rspec:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: run rspec
          command: docker-compose exec web rspec

  rubocop:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

# orbs:jobsのパッケージ
orbs:
  heroku: circleci/heroku@1.2.4

# workflows:jobsの実行順番の操作
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
