version: 2.1
jobs:
  run-tests:
    working_directory: ~/app
    executor:
      name: tests/default
      tag: 2.7.2
      test_db_name: app_name_test
    steps:
      - tests/setup-and-run-tests:
        bundler-version: 2.2.4

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

# orbs:jobsのパッケージ
orbs:
  heroku: circleci/heroku@1.2.4
  tests: zfhui/ruby-tests@0.0.2

# workflows:jobsの実行順番
workflows:
  version: 2.1
  build:
    jobs:
      - run-tests
      - heroku_deploy:
          requires:
            - run-tests
